-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.11.0.396.4
-- Module  Version: 5.7
-- Tue Sep 22 21:57:27 2020

-- parameterized module component declaration
component pll
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        CLKOS: out  std_logic);
end component;

-- parameterized module component instance
__ : pll
    port map (CLKI=>__, CLKOP=>__, CLKOS=>__);
